'==============================Form1.vb=============================='
'  Author:    Connor Group Software Development team 2014            '
'  Copyright: Copyright (C) 2014 Connor Group. All rights reserved.  '
'  Email:     it@connorgp.com                                        '
'  Website:   http://www.connorgp.com                                '
'                                                                    '
'  The copyright to the source code and computer program(s)          '
'  herein is the property of Connor Group.The source code            '
'  and program(s) may be used and/or copied only with the            '
'  written permission of Connor Group or in accordance with          '
'  the terms and conditions stipulated in the                        '
'  agreement/contract under which the source code and                '
'  program(s) have been supplied.                                    '
'                                                                    '
<<<<<<< HEAD
'==============================Form1.vb=============================='
'  Author:    Connor Group Software Development team 2014            '
'  Copyright: Copyright (C) 2014 Connor Group. All rights reserved.  '
'  Email:     it@connorgp.com                                        '
'  Website:   http://www.connorgp.com                                '
'                                                                    '
'  The copyright to the source code and computer program(s)          '
'  herein is the property of Connor Group.The source code            '
'  and program(s) may be used and/or copied only with the            '
'  written permission of Connor Group or in accordance with          '
'  the terms and conditions stipulated in the                        '
'  agreement/contract under which the source code and                '
'  program(s) have been supplied.                                    '
'                                                                    '
<<<<<<< HEAD
'==============================Form1.vb=============================='
'  Author:    Connor Group Software Development team 2014            '
'  Copyright: Copyright (C) 2014 Connor Group. All rights reserved.  '
'  Email:     it@connorgp.com                                        '
'  Website:   http://www.connorgp.com                                '
'                                                                    '
'  The copyright to the source code and computer program(s)          '
'  herein is the property of Connor Group.The source code            '
'  and program(s) may be used and/or copied only with the            '
'  written permission of Connor Group or in accordance with          '
'  the terms and conditions stipulated in the                        '
'  agreement/contract under which the source code and                '
'  program(s) have been supplied.                                    '
'                                                                    '
=======
>>>>>>> 0aeb2c99239193fb2bfbb634e8ff9013cd192ae5
=======
>>>>>>> 38bdafccd2a821f2fa07d302a876f11a6922b02d
Public Class Form1

End Class
